name: Glow Release

on:
  push:
    tags:
      - "release/v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Remove unused build gunk from runner
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Set release version
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/release/}" >> $GITHUB_ENV
      # - name: Test
      #   run: |
      #     echo $RELEASE_VERSION
      #     echo ${{ env.RELEASE_VERSION }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64
          file: testingforpodman2/Dockerfile
          push: true
          tags: |
            ghcr.io/thg-accelerator/${{ github.event.repository.name }}:latest
            ghcr.io/thg-accelerator/${{ github.event.repository.name }}/backend:${{ env.RELEASE_VERSION }}
      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64
          file: frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/thg-accelerator/${{ github.event.repository.name }}:latest
            ghcr.io/thg-accelerator/${{ github.event.repository.name }}/frontend:${{ env.RELEASE_VERSION }}
